// index.js Generated By ChatGPT

const state = {
  items: [
    { id: "001-beetroot", name: "beetroot", price: 0.35, type: "notFruit" },
    { id: "002-carrot", name: "carrot", price: 0.35, type: "notFruit" },
    { id: "003-apple", name: "apple", price: 0.35, type: "fruit" },
    { id: "004-apricot", name: "apricot", price: 0.35, type: "fruit" },
    { id: "005-avocado", name: "avocado", price: 0.35, type: "maybeFruit" },
    { id: "006-bananas", name: "bananas", price: 0.35, type: "maybeFruit" },
    { id: "007-bell-pepper", name: "bell pepper", price: 0.35, type: "notFruit" },
    { id: "008-berry", name: "berry", price: 0.35, type: "notFruit" },
    { id: "009-blueberry", name: "blueberry", price: 0.35, type: "notFruit" },
    { id: "010-eggplant", name: "eggplant", price: 0.35, type: "notFruit" }
  ],
  cart: []
};

// DOM Elements
const storeList = document.querySelector('.store--item-list');
const cartList = document.querySelector('.cart--item-list');
const totalElement = document.querySelector('.total-cost');

// Render Store Items
function renderStoreItems() {
  storeList.innerHTML = '';
  state.items.forEach((item) => {
    const li = document.createElement('li');
    li.innerHTML = `
      <div class="store--item-icon">
        <img src="assets/icons/${item.id}.svg" alt="${item.name}" />
      </div>
      <button data-id="${item.id}" class="add-to-cart-btn">Add to cart</button>
    `;
    storeList.appendChild(li);
  });
}

// Render Cart
function renderCart() {
  cartList.innerHTML = '';
  state.cart.forEach((cartItem) => {
    const li = document.createElement('li');
    li.innerHTML = `
      <img class="cart--item-icon" src="assets/icons/${cartItem.id}.svg" alt="${cartItem.name}" />
      <p>${cartItem.name}</p>
      <button class="quantity-btn remove-btn center" data-id="${cartItem.id}">-</button>
      <span class="quantity-text center">${cartItem.quantity}</span>
      <button class="quantity-btn add-btn center" data-id="${cartItem.id}">+</button>
    `;
    cartList.appendChild(li);
  });
  updateTotal();
}

// Add Item to Cart
function addToCart(itemId) {
  const item = state.items.find((item) => item.id === itemId);
  const cartItem = state.cart.find((ci) => ci.id === itemId);
  
  if (cartItem) {
    cartItem.quantity += 1;
  } else {
    state.cart.push({ ...item, quantity: 1 });
  }
  renderCart();
}

// Remove or Decrease Item in Cart
function updateCartItemQuantity(itemId, delta) {
  const cartItem = state.cart.find((ci) => ci.id === itemId);
  if (cartItem) {
    cartItem.quantity += delta;
    if (cartItem.quantity <= 0) {
      state.cart = state.cart.filter((ci) => ci.id !== itemId);
    }
  }
  renderCart();
}

// Update Total
function updateTotal() {
  const total = state.cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
  totalElement.textContent = `Total: $${total.toFixed(2)}`;
}

// Event Listeners
storeList.addEventListener('click', (event) => {
  if (event.target.classList.contains('add-to-cart-btn')) {
    const itemId = event.target.dataset.id;
    addToCart(itemId);
  }
});

cartList.addEventListener('click', (event) => {
  const itemId = event.target.dataset.id;
  if (event.target.classList.contains('add-btn')) {
    updateCartItemQuantity(itemId, 1);
  } else if (event.target.classList.contains('remove-btn')) {
    updateCartItemQuantity(itemId, -1);
  }
});

// Initial Render
renderStoreItems();
renderCart();
updateTotal();
